// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 59.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'tiled_test';

  static const String assets_images_tile_maps_bamboo_png = 'assets/images/tile_maps/bamboo.png';
  static const String tiled_test$assets_images_tile_maps_bamboo_png = 'packages/tiled_test/assets/images/tile_maps/bamboo.png';

  static const String assets_images_tile_maps_bins_png = 'assets/images/tile_maps/bins.png';
  static const String tiled_test$assets_images_tile_maps_bins_png = 'packages/tiled_test/assets/images/tile_maps/bins.png';

  static const String assets_images_tile_maps_bonsai_png = 'assets/images/tile_maps/bonsai.png';
  static const String tiled_test$assets_images_tile_maps_bonsai_png = 'packages/tiled_test/assets/images/tile_maps/bonsai.png';

  static const String assets_images_tile_maps_bridge_rail_png = 'assets/images/tile_maps/bridge_rail.png';
  static const String tiled_test$assets_images_tile_maps_bridge_rail_png = 'packages/tiled_test/assets/images/tile_maps/bridge_rail.png';

  static const String assets_images_tile_maps_buildings_png = 'assets/images/tile_maps/buildings.png';
  static const String tiled_test$assets_images_tile_maps_buildings_png = 'packages/tiled_test/assets/images/tile_maps/buildings.png';

  static const String assets_images_tile_maps_fence_png = 'assets/images/tile_maps/fence.png';
  static const String tiled_test$assets_images_tile_maps_fence_png = 'packages/tiled_test/assets/images/tile_maps/fence.png';

  static const String assets_images_tile_maps_grass_png = 'assets/images/tile_maps/grass.png';
  static const String tiled_test$assets_images_tile_maps_grass_png = 'packages/tiled_test/assets/images/tile_maps/grass.png';

  static const String assets_images_tile_maps_grass_barriers_png = 'assets/images/tile_maps/grass_barriers.png';
  static const String tiled_test$assets_images_tile_maps_grass_barriers_png = 'packages/tiled_test/assets/images/tile_maps/grass_barriers.png';

  static const String assets_images_tile_maps_houses_japanese_png = 'assets/images/tile_maps/houses_japanese.png';
  static const String tiled_test$assets_images_tile_maps_houses_japanese_png = 'packages/tiled_test/assets/images/tile_maps/houses_japanese.png';

  static const String assets_images_tile_maps_mini_hood_png = 'assets/images/tile_maps/mini_hood.png';
  static const String tiled_test$assets_images_tile_maps_mini_hood_png = 'packages/tiled_test/assets/images/tile_maps/mini_hood.png';

  static const String assets_images_tile_maps_mini_park_png = 'assets/images/tile_maps/mini_park.png';
  static const String tiled_test$assets_images_tile_maps_mini_park_png = 'packages/tiled_test/assets/images/tile_maps/mini_park.png';

  static const String assets_images_tile_maps_objects_grass_png = 'assets/images/tile_maps/objects_grass.png';
  static const String tiled_test$assets_images_tile_maps_objects_grass_png = 'packages/tiled_test/assets/images/tile_maps/objects_grass.png';

  static const String assets_images_tile_maps_objects_street_png = 'assets/images/tile_maps/objects_street.png';
  static const String tiled_test$assets_images_tile_maps_objects_street_png = 'packages/tiled_test/assets/images/tile_maps/objects_street.png';

  static const String assets_images_tile_maps_park_overlay_png = 'assets/images/tile_maps/park_overlay.png';
  static const String tiled_test$assets_images_tile_maps_park_overlay_png = 'packages/tiled_test/assets/images/tile_maps/park_overlay.png';

  static const String assets_images_tile_maps_pavement_png = 'assets/images/tile_maps/pavement.png';
  static const String tiled_test$assets_images_tile_maps_pavement_png = 'packages/tiled_test/assets/images/tile_maps/pavement.png';

  static const String assets_images_tile_maps_rock_wall_png = 'assets/images/tile_maps/rock_wall.png';
  static const String tiled_test$assets_images_tile_maps_rock_wall_png = 'packages/tiled_test/assets/images/tile_maps/rock_wall.png';

  static const String assets_images_tile_maps_room_png = 'assets/images/tile_maps/room.png';
  static const String tiled_test$assets_images_tile_maps_room_png = 'packages/tiled_test/assets/images/tile_maps/room.png';

  static const String assets_images_tile_maps_room_door_png = 'assets/images/tile_maps/room_door.png';
  static const String tiled_test$assets_images_tile_maps_room_door_png = 'packages/tiled_test/assets/images/tile_maps/room_door.png';

  static const String assets_images_tile_maps_sand_png = 'assets/images/tile_maps/sand.png';
  static const String tiled_test$assets_images_tile_maps_sand_png = 'packages/tiled_test/assets/images/tile_maps/sand.png';

  static const String assets_images_tile_maps_street_overlays_png = 'assets/images/tile_maps/street_overlays.png';
  static const String tiled_test$assets_images_tile_maps_street_overlays_png = 'packages/tiled_test/assets/images/tile_maps/street_overlays.png';

  static const String assets_images_tile_maps_table_png = 'assets/images/tile_maps/table.png';
  static const String tiled_test$assets_images_tile_maps_table_png = 'packages/tiled_test/assets/images/tile_maps/table.png';

  static const String assets_images_tile_maps_track_fence_png = 'assets/images/tile_maps/track_fence.png';
  static const String tiled_test$assets_images_tile_maps_track_fence_png = 'packages/tiled_test/assets/images/tile_maps/track_fence.png';

  static const String assets_images_tile_maps_transitions_png = 'assets/images/tile_maps/transitions.png';
  static const String tiled_test$assets_images_tile_maps_transitions_png = 'packages/tiled_test/assets/images/tile_maps/transitions.png';

  static const String assets_images_tile_maps_trees_png = 'assets/images/tile_maps/trees.png';
  static const String tiled_test$assets_images_tile_maps_trees_png = 'packages/tiled_test/assets/images/tile_maps/trees.png';

  static const String assets_images_tile_maps_wall_png = 'assets/images/tile_maps/wall.png';
  static const String tiled_test$assets_images_tile_maps_wall_png = 'packages/tiled_test/assets/images/tile_maps/wall.png';

  static const String assets_images_tile_maps_wall_thick_png = 'assets/images/tile_maps/wall_thick.png';
  static const String tiled_test$assets_images_tile_maps_wall_thick_png = 'packages/tiled_test/assets/images/tile_maps/wall_thick.png';

  static const String assets_images_tile_maps_water_png = 'assets/images/tile_maps/water.png';
  static const String tiled_test$assets_images_tile_maps_water_png = 'packages/tiled_test/assets/images/tile_maps/water.png';

  static const String assets_images_tile_maps_waterfront_png = 'assets/images/tile_maps/waterfront.png';
  static const String tiled_test$assets_images_tile_maps_waterfront_png = 'packages/tiled_test/assets/images/tile_maps/waterfront.png';

  static const String assets_images_tile_maps_wood_base_png = 'assets/images/tile_maps/wood_base.png';
  static const String tiled_test$assets_images_tile_maps_wood_base_png = 'packages/tiled_test/assets/images/tile_maps/wood_base.png';

  static const String assets_tiles_bamboo_tsx = 'assets/tiles/bamboo.tsx';
  static const String tiled_test$assets_tiles_bamboo_tsx = 'packages/tiled_test/assets/tiles/bamboo.tsx';

  static const String assets_tiles_bins_tsx = 'assets/tiles/bins.tsx';
  static const String tiled_test$assets_tiles_bins_tsx = 'packages/tiled_test/assets/tiles/bins.tsx';

  static const String assets_tiles_bonsai_tsx = 'assets/tiles/bonsai.tsx';
  static const String tiled_test$assets_tiles_bonsai_tsx = 'packages/tiled_test/assets/tiles/bonsai.tsx';

  static const String assets_tiles_bridge_rail_tsx = 'assets/tiles/bridge_rail.tsx';
  static const String tiled_test$assets_tiles_bridge_rail_tsx = 'packages/tiled_test/assets/tiles/bridge_rail.tsx';

  static const String assets_tiles_buildings_tsx = 'assets/tiles/buildings.tsx';
  static const String tiled_test$assets_tiles_buildings_tsx = 'packages/tiled_test/assets/tiles/buildings.tsx';

  static const String assets_tiles_fence_tsx = 'assets/tiles/fence.tsx';
  static const String tiled_test$assets_tiles_fence_tsx = 'packages/tiled_test/assets/tiles/fence.tsx';

  static const String assets_tiles_grass_tsx = 'assets/tiles/grass.tsx';
  static const String tiled_test$assets_tiles_grass_tsx = 'packages/tiled_test/assets/tiles/grass.tsx';

  static const String assets_tiles_grass_barriers_tsx = 'assets/tiles/grass_barriers.tsx';
  static const String tiled_test$assets_tiles_grass_barriers_tsx = 'packages/tiled_test/assets/tiles/grass_barriers.tsx';

  static const String assets_tiles_hood_tmx = 'assets/tiles/hood.tmx';
  static const String tiled_test$assets_tiles_hood_tmx = 'packages/tiled_test/assets/tiles/hood.tmx';

  static const String assets_tiles_lights_tsx = 'assets/tiles/lights.tsx';
  static const String tiled_test$assets_tiles_lights_tsx = 'packages/tiled_test/assets/tiles/lights.tsx';

  static const String assets_tiles_objects_grass_tsx = 'assets/tiles/objects_grass.tsx';
  static const String tiled_test$assets_tiles_objects_grass_tsx = 'packages/tiled_test/assets/tiles/objects_grass.tsx';

  static const String assets_tiles_objects_street_tsx = 'assets/tiles/objects_street.tsx';
  static const String tiled_test$assets_tiles_objects_street_tsx = 'packages/tiled_test/assets/tiles/objects_street.tsx';

  static const String assets_tiles_park_tmx = 'assets/tiles/park.tmx';
  static const String tiled_test$assets_tiles_park_tmx = 'packages/tiled_test/assets/tiles/park.tmx';

  static const String assets_tiles_park_overlay_tsx = 'assets/tiles/park_overlay.tsx';
  static const String tiled_test$assets_tiles_park_overlay_tsx = 'packages/tiled_test/assets/tiles/park_overlay.tsx';

  static const String assets_tiles_pavement_tsx = 'assets/tiles/pavement.tsx';
  static const String tiled_test$assets_tiles_pavement_tsx = 'packages/tiled_test/assets/tiles/pavement.tsx';

  static const String assets_tiles_rock_wall_tsx = 'assets/tiles/rock_wall.tsx';
  static const String tiled_test$assets_tiles_rock_wall_tsx = 'packages/tiled_test/assets/tiles/rock_wall.tsx';

  static const String assets_tiles_room_tmx = 'assets/tiles/room.tmx';
  static const String tiled_test$assets_tiles_room_tmx = 'packages/tiled_test/assets/tiles/room.tmx';

  static const String assets_tiles_room_door_tsx = 'assets/tiles/room_door.tsx';
  static const String tiled_test$assets_tiles_room_door_tsx = 'packages/tiled_test/assets/tiles/room_door.tsx';

  static const String assets_tiles_room_tiles_tsx = 'assets/tiles/room_tiles.tsx';
  static const String tiled_test$assets_tiles_room_tiles_tsx = 'packages/tiled_test/assets/tiles/room_tiles.tsx';

  static const String assets_tiles_sand_tsx = 'assets/tiles/sand.tsx';
  static const String tiled_test$assets_tiles_sand_tsx = 'packages/tiled_test/assets/tiles/sand.tsx';

  static const String assets_tiles_street_overlays_tsx = 'assets/tiles/street_overlays.tsx';
  static const String tiled_test$assets_tiles_street_overlays_tsx = 'packages/tiled_test/assets/tiles/street_overlays.tsx';

  static const String assets_tiles_table_tsx = 'assets/tiles/table.tsx';
  static const String tiled_test$assets_tiles_table_tsx = 'packages/tiled_test/assets/tiles/table.tsx';

  static const String assets_tiles_track_fence_tsx = 'assets/tiles/track_fence.tsx';
  static const String tiled_test$assets_tiles_track_fence_tsx = 'packages/tiled_test/assets/tiles/track_fence.tsx';

  static const String assets_tiles_transitions_tsx = 'assets/tiles/transitions.tsx';
  static const String tiled_test$assets_tiles_transitions_tsx = 'packages/tiled_test/assets/tiles/transitions.tsx';

  static const String assets_tiles_trees_tsx = 'assets/tiles/trees.tsx';
  static const String tiled_test$assets_tiles_trees_tsx = 'packages/tiled_test/assets/tiles/trees.tsx';

  static const String assets_tiles_wall_tsx = 'assets/tiles/wall.tsx';
  static const String tiled_test$assets_tiles_wall_tsx = 'packages/tiled_test/assets/tiles/wall.tsx';

  static const String assets_tiles_wall_thick_tsx = 'assets/tiles/wall_thick.tsx';
  static const String tiled_test$assets_tiles_wall_thick_tsx = 'packages/tiled_test/assets/tiles/wall_thick.tsx';

  static const String assets_tiles_water_tsx = 'assets/tiles/water.tsx';
  static const String tiled_test$assets_tiles_water_tsx = 'packages/tiled_test/assets/tiles/water.tsx';

  static const String assets_tiles_waterfront_tsx = 'assets/tiles/waterfront.tsx';
  static const String tiled_test$assets_tiles_waterfront_tsx = 'packages/tiled_test/assets/tiles/waterfront.tsx';

  static const String assets_tiles_wood_base_tsx = 'assets/tiles/wood_base.tsx';
  static const String tiled_test$assets_tiles_wood_base_tsx = 'packages/tiled_test/assets/tiles/wood_base.tsx';
}
